stages:
        - create
        - apply
        - destroy

image: 
        name: hashicorp/terraform:light
        entrypoint: [""]
   
build:
        stage: create
        tags:
                - exam
        script:
                - terraform init .
                - terraform validate .

publish:
        stage: apply
        tags:
                - exam
        script:
                - terraform init -var="group_id=s6" .
                - terraform apply -var="group_id=s6" -auto-approve .
        artifacts:
                name: "$CI_JOB_NAME-$CI_COMMIT_TAG"
                paths:
                        - public
                expire_in: 15 days

remove:
        stage: destroy
        tags:
                - exam
        script:
                - terraform init .
                - terraform destroy -var="group_id=s6" -auto-approve .
